package:
  name: assimp
  version: 3.0.1270

source:
  fn: assimp--3.0.1270-source-only.zip 
  url: http://sourceforge.net/projects/assimp/files/assimp-3.0/assimp--3.0.1270-source-only.zip/download
  md5: 52aa4cf4e34e6b2a9c5f6c0b3c319af1 

  patches:
   - osx.patch [osx]

requirements:
  build:
    - cmake [win]
  
about:
  home: http://assimp.sourceforge.net/
  license: BSD
